//
//  ForeCastWorker.swift
//  WeatherApp
//
//  Created by Sahassawat on 15/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Moya

class ForeCastWorker {
    
      func fetchForecast(lat: Double, lon: Double, apiKey: String , completion: @escaping (Result<ForecastDataResponse?>) ->()) {
          let target = WeatherTargetType.getForecast(lat: lat, lon: lon, apiKey: apiKey)
          MoyaService<ForecastDataResponse>.getRequest(target: target) { result in
              switch result {
                  
              case .success(result: let result):
                  completion(.success(result: result))
              case .failure(error: let error):
                  completion(.failure(error: error))
              }
          }
      }

}
