//
//  ForeCastViewController.swift
//  WeatherApp
//
//  Created by Sahassawat on 15/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForeCastDisplayLogic: AnyObject {
  func displayForecast(viewModel: ForeCast.GetForeCast.ViewModel)
}

class ForeCastViewController: UIViewController, ForeCastDisplayLogic {
  var interactor: ForeCastBusinessLogic?
  var router: (NSObjectProtocol & ForeCastRoutingLogic & ForeCastDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ForeCastInteractor()
    let presenter = ForeCastPresenter()
    let router = ForeCastRouter()
    let worker = ForeCastWorker()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    interactor.worker = worker
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
      
  }
  
 
  // MARK: View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething() {
    let request = ForeCast.GetForeCast.Request()
    interactor?.getForecast(request: request)
  }
  
  func displayForecast(viewModel: ForeCast.GetForeCast.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
