//
//  ForeCastInteractor.swift
//  WeatherApp
//
//  Created by Sahassawat on 15/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForeCastBusinessLogic
{
  func doSomething(request: ForeCast.Something.Request)
}

protocol ForeCastDataStore {
    var lon: Double { get set }
    var lat: Double { get set }
}

class ForeCastInteractor: ForeCastBusinessLogic, ForeCastDataStore
{
  var presenter: ForeCastPresentationLogic?
  var worker: ForeCastWorker?
  var lon: Double = 0.0
  var lat: Double = 0.0
  
  // MARK: Do something
  
  func doSomething(request: ForeCast.Something.Request)
  {
    worker = ForeCastWorker()
    worker?.doSomeWork()
    
    let response = ForeCast.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
