//
//  WeatherWorker.swift
//  WeatherApp
//
//  Created by Sahassawat on 14/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Moya

class WeatherWorker
{
    static var provider = MoyaProvider<MultiTarget>()
    
    func fetchWeather(city: String, apiKey: String , completion: @escaping (Result<WeatherDataResponse?>) ->()) {
        let target = WeatherTargetType.getWeatherByCityName(city: city, apiKey: apiKey)
        MoyaService<WeatherDataResponse>.getRequest(target: target) { result in
            switch result {
                
            case .success(result: let result):
                completion(.success(result: result))
            case .failure(error: let error):
                completion(.failure(error: error))
            }
        }
    }
}
