//
//  WeatherInteractor.swift
//  WeatherApp
//
//  Created by Sahassawat on 14/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherBusinessLogic
{
    func getWeatherByCity(request: Weather.GetWeather.Request)
}

protocol WeatherDataStore {
    //var name: String { get set }
}

class WeatherInteractor: WeatherBusinessLogic, WeatherDataStore {
    var presenter: WeatherPresentationLogic?
    var worker: WeatherWorker?
    var apiKey = "4b65dedcdc183d4f99918a6bb9cfeb62"
    
    // MARK: Do something
    
    func getWeatherByCity(request: Weather.GetWeather.Request) {
        
        worker?.fetchWeather(city: request.city, apiKey: apiKey, completion: { result in
            switch result {
            case .success(let result):
                if let response = result {
                    self.presenter?.presentWeatherByCity(response: .init(result: .success(result: response)))
                    
                }
            case .failure(error: let error):
                self.presenter?.presentWeatherByCity(response: .init(result: .failure(error: error)))
            }
        })
    }
}
