//
//  WeatherPresenter.swift
//  WeatherApp
//
//  Created by Sahassawat on 14/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherPresentationLogic
{
  func presentSomething(response: Weather.Something.Response)
}

class WeatherPresenter: WeatherPresentationLogic
{
  weak var viewController: WeatherDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Weather.Something.Response)
  {
    let viewModel = Weather.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
