//
//  WeatherRouter.swift
//  WeatherApp
//
//  Created by Sahassawat on 14/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WeatherRoutingLogic
{
    func routeToForecast()
}

protocol WeatherDataPassing
{
  var dataStore: WeatherDataStore? { get }
}

class WeatherRouter: BaseRouter, WeatherRoutingLogic, WeatherDataPassing {

  var dataStore: WeatherDataStore?
  
  // MARK: Routing
  
    func routeToForecast() {
        let vc = getViewController(storyboard: .Forecast, expectedVC: ForeCastViewController.self)
        var destination = vc.router?.dataStore
        destination?.lat = dataStore?.lat ?? 0.0
        destination?.lon = dataStore?.lon ?? 0.0
        pushViewController(vc)
    }
}
