//
//  WeatherModels.swift
//  WeatherApp
//
//  Created by Sahassawat on 14/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Weather
{
  // MARK: Use cases
  
    enum GetWeather {
        struct Request {
            let city: String
        }
        struct Response {
            let result: UserResult<WeatherDataResponse>
        }
        struct ViewModel {
            let content: Content<WeatherModel, Error>
        }
    }
    
    enum CalulateFahrenheit {
        struct Request {
            let celsius: String
        }
        struct Response {
            let resultFahrenheit: Double
        }
        struct ViewModel {
            let resultFahrenheit: String
        }
    }
}

struct WeatherModel {
    let conditionId: Int
    let cityName: String
    let temperature: Double
    let humidity: Int
    var date: String? = ""
    
    var temperatureString: String {
        return String(format: "%.1f", temperature)
    }
    
    var humidityString: String {
        return String(humidity)
    }
    
    var conditionName: String {
        switch conditionId {
        case 200...232:
            return "cloud.bolt"
        case 300...321:
            return "cloud.drizzle"
        case 500...531:
            return "cloud.rain"
        case 600...622:
            return "cloud.snow"
        case 701...781:
            return "cloud.fog"
        case 800:
            return "sun.max"
        case 801...804:
            return "cloud.bolt"
        default:
            return "cloud"
        }
    }
    
}
