//
//  WeatherInteractor.swift
//  WeatherApp
//
//  Created by Sahassawat on 14/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherBusinessLogic
{
  func doSomething(request: Weather.Something.Request)
}

protocol WeatherDataStore
{
  //var name: String { get set }
}

class WeatherInteractor: WeatherBusinessLogic, WeatherDataStore
{
  var presenter: WeatherPresentationLogic?
  var worker: WeatherWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Weather.Something.Request)
  {
    worker = WeatherWorker()
    worker?.doSomeWork()
    
    let response = Weather.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
